package com.hull.entity;

import com.hull.common.IdEntity;

import java.util.Date;

/**
WARNING: 
this code is generated by CodeMonkey
please DO NOT modify this file
**/
public class UserInfo extends IdEntity {
  private String name;
  private String password;
  /**
  识别码
  **/
  private String verifyCode;
  private String mobile;
  private Date created;
  private Date modified;

  public String getName() {
  	return name;
  }
	
  public void setName(String name) {
    this.name = name;
  }
	
  public String getPassword() {
  	return password;
  }
	
  public void setPassword(String password) {
    this.password = password;
  }
	
  public String getVerifyCode() {
  	return verifyCode;
  }
	
  public void setVerifyCode(String verifyCode) {
    this.verifyCode = verifyCode;
  }
	
  public String getMobile() {
  	return mobile;
  }
	
  public void setMobile(String mobile) {
    this.mobile = mobile;
  }

  public Date getCreated() {
    return created;
  }

  public void setCreated(Date created) {
    this.created = created;
  }

  public Date getModified() {
    return modified;
  }

  public void setModified(Date modified) {
    this.modified = modified;
  }
}
