package com.hull.mapper;


import com.hull.common.BaseMapper;
import com.hull.entity.PwdInfo;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
warning
This file is generated by CodeMonkey
Please DO NOT modify this file
**/

@Repository
public interface PwdInfoBaseMapper extends BaseMapper<Long,PwdInfo> {

    List<PwdInfo> select(PwdInfo pwdInfo);
}