package com.hull.entity;

import com.hull.common.IdEntity;

/**
WARNING: 
this code is generated by CodeMonkey
please DO NOT modify this file
**/
public class ClassInfo extends IdEntity {
  /**
  教室编号
  **/
  private String classNo;
  /**
  教室名称
  **/
  private String className;
  /**
  类型 01-大 02-中 03-小
  **/
  private String type;
  /**
  状态 1-可用 0 不可用
  **/
  private String status;
  /**
  可用时间段
  **/
  private String allowTime;

  public String getClassNo() {
  	return classNo;
  }
	
  public void setClassNo(String classNo) {
    this.classNo = classNo;
  }
	
  public String getClassName() {
  	return className;
  }
	
  public void setClassName(String className) {
    this.className = className;
  }
	
  public String getType() {
  	return type;
  }
	
  public void setType(String type) {
    this.type = type;
  }
	
  public String getStatus() {
  	return status;
  }
	
  public void setStatus(String status) {
    this.status = status;
  }
	
  public String getAllowTime() {
  	return allowTime;
  }
	
  public void setAllowTime(String allowTime) {
    this.allowTime = allowTime;
  }
	
}
