package com.hull.entity;

import com.hull.common.IdEntity;

import java.util.Date;

/**
WARNING: 
this code is generated by CodeMonkey
please DO NOT modify this file
**/
public class ClassOrderInfo extends IdEntity {
  /**
  会议室ID
  **/
  private Integer classId;
  /**
  预约人
  **/
  private Integer orderStaff;
  /**
  参会团队ID
  **/
  private Integer teamId;
  /**
  状态  0-已申请 1-审批通过 2-审批未通过
  **/
  private String status;
  /**
  会议时间段
  **/
  private String meetingTime;
  private Date createTime;
  private Date updateTime;

  public Integer getClassId() {
  	return classId;
  }
	
  public void setClassId(Integer classId) {
    this.classId = classId;
  }
	
  public Integer getOrderStaff() {
  	return orderStaff;
  }
	
  public void setOrderStaff(Integer orderStaff) {
    this.orderStaff = orderStaff;
  }
	
  public Integer getTeamId() {
  	return teamId;
  }
	
  public void setTeamId(Integer teamId) {
    this.teamId = teamId;
  }
	
  public String getStatus() {
  	return status;
  }
	
  public void setStatus(String status) {
    this.status = status;
  }
	
  public String getMeetingTime() {
  	return meetingTime;
  }
	
  public void setMeetingTime(String meetingTime) {
    this.meetingTime = meetingTime;
  }
	
  public Date getCreateTime() {
  	return createTime;
  }
	
  public void setCreateTime(Date createTime) {
    this.createTime = createTime;
  }
	
  public Date getUpdateTime() {
  	return updateTime;
  }
	
  public void setUpdateTime(Date updateTime) {
    this.updateTime = updateTime;
  }
	
}
