package com.hull.entity;

import com.hull.common.IdEntity;

import java.util.Date;

/**
WARNING: 
this code is generated by CodeMonkey
please DO NOT modify this file
**/
public class ClassOrderInfo extends IdEntity {
  /**
  会议室ID
  **/
  private Integer classId;
  /**
   * 会议主题
   */
  private String meetingTopic;

  /**
   会议时间段
   **/
  private Integer meetingTimeId;
  /**
  预约人
  **/
  private Integer orderStaffId;
  /**
  参会团队ID
  **/
  private Integer teamId;
  /**
  状态  0-已申请 1-审批通过 2-审批未通过
  **/
  private String status;
  private Date createTime;
  private Date updateTime;

  public Integer getClassId() {
  	return classId;
  }

  public String getMeetingTopic() {
    return meetingTopic;
  }

  public void setMeetingTopic(String meetingTopic) {
    this.meetingTopic = meetingTopic;
  }

  public void setClassId(Integer classId) {
    this.classId = classId;
  }
	
  public Integer getOrderStaffId() {
  	return orderStaffId;
  }
	
  public void setOrderStaffId(Integer orderStaffId) {
    this.orderStaffId = orderStaffId;
  }
	
  public Integer getTeamId() {
  	return teamId;
  }
	
  public void setTeamId(Integer teamId) {
    this.teamId = teamId;
  }
	
  public String getStatus() {
  	return status;
  }
	
  public void setStatus(String status) {
    this.status = status;
  }
	
  public Integer getMeetingTimeId() {
  	return meetingTimeId;
  }
	
  public void setMeetingTimeId(Integer meetingTimeId) {
    this.meetingTimeId = meetingTimeId;
  }
	
  public Date getCreateTime() {
  	return createTime;
  }
	
  public void setCreateTime(Date createTime) {
    this.createTime = createTime;
  }
	
  public Date getUpdateTime() {
  	return updateTime;
  }
	
  public void setUpdateTime(Date updateTime) {
    this.updateTime = updateTime;
  }
	
}
