package com.hull.entity;

import com.hull.common.IdEntity;

/**
WARNING: 
this code is generated by CodeMonkey
please DO NOT modify this file
**/
public class MeetingUnit extends IdEntity {
  private String timeUnit;

  public String getTimeUnit() {
  	return timeUnit;
  }
	
  public void setTimeUnit(String timeUnit) {
    this.timeUnit = timeUnit;
  }
	
}
