package com.hull.entity;

import com.hull.common.IdEntity;

/**
WARNING: 
this code is generated by CodeMonkey
please DO NOT modify this file
**/
public class Role extends IdEntity {
  /**
  角色名称
  **/
  private String roleName;

  public String getRoleName() {
  	return roleName;
  }
	
  public void setRoleName(String roleName) {
    this.roleName = roleName;
  }
	
}
