package com.hull.entity;

import com.hull.common.IdEntity;

/**
WARNING: 
this code is generated by CodeMonkey
please DO NOT modify this file
**/
public class StaffInfo extends IdEntity {
  /**
  姓名
  **/
  private String name;
  /**
  密码
  **/
  private String password;
  /**
   * 性别
   */
  private Integer sex;
  /**
  邮箱
  **/
  private String email;
  /**
   * 手机号
   */
  private String mobile;

  /**
  班级ID
  **/
  private Integer teamId;
  /**
  角色ID
  **/
  private Integer roleId;

  public String getName() {
  	return name;
  }
	
  public void setName(String name) {
    this.name = name;
  }
	
  public String getPassword() {
  	return password;
  }
	
  public void setPassword(String password) {
    this.password = password;
  }

  public Integer getSex() {
    return sex;
  }

  public void setSex(Integer sex) {
    this.sex = sex;
  }

  public String getEmail() {
  	return email;
  }
	
  public void setEmail(String email) {
    this.email = email;
  }

  public String getMobile() {
    return mobile;
  }

  public void setMobile(String mobile) {
    this.mobile = mobile;
  }

  public Integer getTeamId() {
  	return teamId;
  }
	
  public void setTeamId(Integer teamId) {
    this.teamId = teamId;
  }
	
  public Integer getRoleId() {
  	return roleId;
  }
	
  public void setRoleId(Integer roleId) {
    this.roleId = roleId;
  }
	
}
