package com.hull.entity;

import com.hull.common.IdEntity;

/**
WARNING: 
this code is generated by CodeMonkey
please DO NOT modify this file
**/
public class TeamInfo extends IdEntity {
  /**
  小组名称
  **/
  private String teamName;
  private String teamCode;

  public String getTeamName() {
  	return teamName;
  }
	
  public void setTeamName(String teamName) {
    this.teamName = teamName;
  }
	
  public String getTeamCode() {
  	return teamCode;
  }
	
  public void setTeamCode(String teamCode) {
    this.teamCode = teamCode;
  }
	
}
