package com.hull.entity;

import com.hull.common.IdEntity;

import java.util.Date;

/**
WARNING: 
this code is generated by CodeMonkey
please DO NOT modify this file
**/
public class CustomerInfo extends IdEntity {
  /**
  登陆名
  **/
  private String name;
  private String realName;
  /**
  密码
  **/
  private String password;
  /**
  性别 1-男 0-女
  **/
  private Integer sex;
  /**
  邮箱
  **/
  private String email;
  /**
  手机号
  **/
  private String mobile;
  /**
  地址
  **/
  private String address;
  /**
  角色ID
  **/
  private Integer roleId;
  private Date createTime;
  private Date updateTime;

  public String getName() {
  	return name;
  }
	
  public void setName(String name) {
    this.name = name;
  }
	
  public String getRealName() {
  	return realName;
  }
	
  public void setRealName(String realName) {
    this.realName = realName;
  }
	
  public String getPassword() {
  	return password;
  }
	
  public void setPassword(String password) {
    this.password = password;
  }
	
  public Integer getSex() {
  	return sex;
  }
	
  public void setSex(Integer sex) {
    this.sex = sex;
  }
	
  public String getEmail() {
  	return email;
  }
	
  public void setEmail(String email) {
    this.email = email;
  }
	
  public String getMobile() {
  	return mobile;
  }
	
  public void setMobile(String mobile) {
    this.mobile = mobile;
  }
	
  public String getAddress() {
  	return address;
  }
	
  public void setAddress(String address) {
    this.address = address;
  }
	
  public Integer getRoleId() {
  	return roleId;
  }
	
  public void setRoleId(Integer roleId) {
    this.roleId = roleId;
  }
	
  public Date getCreateTime() {
  	return createTime;
  }
	
  public void setCreateTime(Date createTime) {
    this.createTime = createTime;
  }
	
  public Date getUpdateTime() {
  	return updateTime;
  }
	
  public void setUpdateTime(Date updateTime) {
    this.updateTime = updateTime;
  }
	
}
