package com.hull.entity;

import com.hull.common.IdEntity;

import java.math.BigDecimal;
import java.util.Date;

/**
WARNING: 
this code is generated by CodeMonkey
please DO NOT modify this file
**/
public class OrderItem extends IdEntity {
  /**
  订单ID
  **/
  private Integer orderId;
  /**
  商品ID
  **/
  private Integer prodId;
  /**
  商品数量
  **/
  private Integer prodNum;
  /**
  总价
  **/
  private BigDecimal amount;
  private Date createTime;
  private Date updateTime;

  public Integer getOrderId() {
  	return orderId;
  }
	
  public void setOrderId(Integer orderId) {
    this.orderId = orderId;
  }
	
  public Integer getProdId() {
  	return prodId;
  }
	
  public void setProdId(Integer prodId) {
    this.prodId = prodId;
  }
	
  public Integer getProdNum() {
  	return prodNum;
  }
	
  public void setProdNum(Integer prodNum) {
    this.prodNum = prodNum;
  }
	
  public BigDecimal getAmount() {
  	return amount;
  }
	
  public void setAmount(BigDecimal amount) {
    this.amount = amount;
  }
	
  public Date getCreateTime() {
  	return createTime;
  }
	
  public void setCreateTime(Date createTime) {
    this.createTime = createTime;
  }
	
  public Date getUpdateTime() {
  	return updateTime;
  }
	
  public void setUpdateTime(Date updateTime) {
    this.updateTime = updateTime;
  }
	
}
