package com.hull.entity;

import com.hull.common.IdEntity;

import java.math.BigDecimal;
import java.util.Date;

/**
WARNING: 
this code is generated by CodeMonkey
please DO NOT modify this file
**/
public class ProdInfo extends IdEntity {
  /**
  商品名称
  **/
  private String prodName;
  /**
  进货价格
  **/
  private BigDecimal buyPrice;
  /**
  售价
  **/
  private BigDecimal salePrice;
  /**
  库存
  **/
  private Integer stock;
  /**
  单位
  **/
  private String unit;
  private Date createTime;
  private Date updateTime;

  public String getProdName() {
  	return prodName;
  }
	
  public void setProdName(String prodName) {
    this.prodName = prodName;
  }
	
  public BigDecimal getBuyPrice() {
  	return buyPrice;
  }
	
  public void setBuyPrice(BigDecimal buyPrice) {
    this.buyPrice = buyPrice;
  }
	
  public BigDecimal getSalePrice() {
  	return salePrice;
  }
	
  public void setSalePrice(BigDecimal salePrice) {
    this.salePrice = salePrice;
  }
	
  public Integer getStock() {
  	return stock;
  }
	
  public void setStock(Integer stock) {
    this.stock = stock;
  }
	
  public String getUnit() {
  	return unit;
  }
	
  public void setUnit(String unit) {
    this.unit = unit;
  }
	
  public Date getCreateTime() {
  	return createTime;
  }
	
  public void setCreateTime(Date createTime) {
    this.createTime = createTime;
  }
	
  public Date getUpdateTime() {
  	return updateTime;
  }
	
  public void setUpdateTime(Date updateTime) {
    this.updateTime = updateTime;
  }
	
}
