package com.hull.entity;


import com.hull.common.IdEntity;

/**
WARNING: 
this code is generated by CodeMonkey
please DO NOT modify this file
**/
public class UnitInfo extends IdEntity {
  /**
  名称
  **/
  private String name;

  public String getName() {
  	return name;
  }
	
  public void setName(String name) {
    this.name = name;
  }
	
}
