package com.hull.mapper;

import com.hull.common.BaseMapper;
import com.hull.entity.OrderInfo;
import org.springframework.stereotype.Repository;

/**
warning
This file is generated by CodeMonkey
Please DO NOT modify this file
**/
@Repository
public interface OrderInfoBaseMapper extends BaseMapper<Long,OrderInfo> {

}