package com.hull.mapper;

import com.hull.common.BaseMapper;
import com.hull.entity.ProdInfo;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
warning
This file is generated by CodeMonkey
Please DO NOT modify this file
**/
@Repository
public interface ProdInfoBaseMapper extends BaseMapper<Long,ProdInfo> {

    List<ProdInfo> select(ProdInfo prodInfo);
}