package com.hull.mapper;

import com.hull.common.BaseMapper;
import com.hull.entity.Role;
import org.springframework.stereotype.Repository;

/**
warning
This file is generated by CodeMonkey
Please DO NOT modify this file
**/
@Repository
public interface RoleBaseMapper extends BaseMapper<Long,Role> {

}