package com.hull.mapper;

import com.hull.common.BaseMapper;
import com.hull.entity.UnitInfo;
import org.springframework.stereotype.Repository;

/**
warning
This file is generated by CodeMonkey
Please DO NOT modify this file
**/

@Repository
public interface UnitInfoBaseMapper extends BaseMapper<Long,UnitInfo> {

}