package com.hull.entity;

import com.hull.common.BaseEntity;

/**
WARNING: 
this code is generated by CodeMonkey
please DO NOT modify this file
**/
public class StudentScore extends BaseEntity {
  /**
  学号
  **/
  private String studentId;
  /**
  姓名
  **/
  private String studentName;
  /**
  总分
  **/
  private Integer totalScore;
  /**
  门数
  **/
  private Integer lessonNum;
  /**
  性别
  **/
  private String sex;
  /**
  总学分
  **/
  private Integer totalCredit;
  /**
  学分加权平均分
  **/
  private Integer averageCredit;
  /**
  班级排名
  **/
  private Integer ranking;
  /**
  大学英语（一）
  **/
  private Integer english1;
  /**
  大学英语（二）
  **/
  private Integer english2;
  /**
  大学英语（三）
  **/
  private Integer english3;
  /**
  高数1-1
  **/
  private Integer math11;
  /**
  高数1-2
  **/
  private Integer math12;
  /**
  线性代数
  **/
  private Integer linearMath;
  /**
  高级语言程序设计 
  **/
  private Integer languageDesign;
  /**
  高级语言程序设计实验 
  **/
  private Integer languageDesignTest;
  /**
  面向对象程序设计 
  **/
  private Integer objectLanguageDesign;
  /**
  程序设计训练 
  **/
  private Integer languageDesignTrain;
  /**
  数字系统与逻辑设计 
  **/
  private Integer digitalSystermDesign;
  /**
  数字系统与逻辑设计实验 
  **/
  private Integer digitalSystermDesignTest;
  /**
  思想道德修养与法律基础 
  **/
  private Integer moralAndLaw;
  /**
  中国近现代史纲要 
  **/
  private Integer chineseHistory;
  /**
  马克思主义基本原理概论 
  **/
  private Integer maxTheory;
  /**
  体育1 
  **/
  private Integer sports;
  /**
  大学生职业生涯规划 
  **/
  private Integer professionPlan;
  /**
  大学生心理健康 
  **/
  private Integer mindHealth;

  public String getStudentId() {
  	return studentId;
  }
	
  public void setStudentId(String studentId) {
    this.studentId = studentId;
  }
	
  public String getStudentName() {
  	return studentName;
  }
	
  public void setStudentName(String studentName) {
    this.studentName = studentName;
  }
	
  public Integer getTotalScore() {
  	return totalScore;
  }
	
  public void setTotalScore(Integer totalScore) {
    this.totalScore = totalScore;
  }
	
  public Integer getLessonNum() {
  	return lessonNum;
  }
	
  public void setLessonNum(Integer lessonNum) {
    this.lessonNum = lessonNum;
  }
	
  public String getSex() {
  	return sex;
  }
	
  public void setSex(String sex) {
    this.sex = sex;
  }
	
  public Integer getTotalCredit() {
  	return totalCredit;
  }
	
  public void setTotalCredit(Integer totalCredit) {
    this.totalCredit = totalCredit;
  }
	
  public Integer getAverageCredit() {
  	return averageCredit;
  }
	
  public void setAverageCredit(Integer averageCredit) {
    this.averageCredit = averageCredit;
  }
	
  public Integer getRanking() {
  	return ranking;
  }
	
  public void setRanking(Integer ranking) {
    this.ranking = ranking;
  }
	
  public Integer getEnglish1() {
  	return english1;
  }
	
  public void setEnglish1(Integer english1) {
    this.english1 = english1;
  }
	
  public Integer getEnglish2() {
  	return english2;
  }
	
  public void setEnglish2(Integer english2) {
    this.english2 = english2;
  }
	
  public Integer getEnglish3() {
  	return english3;
  }
	
  public void setEnglish3(Integer english3) {
    this.english3 = english3;
  }
	
  public Integer getMath11() {
  	return math11;
  }
	
  public void setMath11(Integer math11) {
    this.math11 = math11;
  }
	
  public Integer getMath12() {
  	return math12;
  }
	
  public void setMath12(Integer math12) {
    this.math12 = math12;
  }
	
  public Integer getLinearMath() {
  	return linearMath;
  }
	
  public void setLinearMath(Integer linearMath) {
    this.linearMath = linearMath;
  }
	
  public Integer getLanguageDesign() {
  	return languageDesign;
  }
	
  public void setLanguageDesign(Integer languageDesign) {
    this.languageDesign = languageDesign;
  }
	
  public Integer getLanguageDesignTest() {
  	return languageDesignTest;
  }
	
  public void setLanguageDesignTest(Integer languageDesignTest) {
    this.languageDesignTest = languageDesignTest;
  }
	
  public Integer getObjectLanguageDesign() {
  	return objectLanguageDesign;
  }
	
  public void setObjectLanguageDesign(Integer objectLanguageDesign) {
    this.objectLanguageDesign = objectLanguageDesign;
  }
	
  public Integer getLanguageDesignTrain() {
  	return languageDesignTrain;
  }
	
  public void setLanguageDesignTrain(Integer languageDesignTrain) {
    this.languageDesignTrain = languageDesignTrain;
  }
	
  public Integer getDigitalSystermDesign() {
  	return digitalSystermDesign;
  }
	
  public void setDigitalSystermDesign(Integer digitalSystermDesign) {
    this.digitalSystermDesign = digitalSystermDesign;
  }
	
  public Integer getDigitalSystermDesignTest() {
  	return digitalSystermDesignTest;
  }
	
  public void setDigitalSystermDesignTest(Integer digitalSystermDesignTest) {
    this.digitalSystermDesignTest = digitalSystermDesignTest;
  }
	
  public Integer getMoralAndLaw() {
  	return moralAndLaw;
  }
	
  public void setMoralAndLaw(Integer moralAndLaw) {
    this.moralAndLaw = moralAndLaw;
  }
	
  public Integer getChineseHistory() {
  	return chineseHistory;
  }
	
  public void setChineseHistory(Integer chineseHistory) {
    this.chineseHistory = chineseHistory;
  }
	
  public Integer getMaxTheory() {
  	return maxTheory;
  }
	
  public void setMaxTheory(Integer maxTheory) {
    this.maxTheory = maxTheory;
  }
	
  public Integer getSports() {
  	return sports;
  }
	
  public void setSports(Integer sports) {
    this.sports = sports;
  }
	
  public Integer getProfessionPlan() {
  	return professionPlan;
  }
	
  public void setProfessionPlan(Integer professionPlan) {
    this.professionPlan = professionPlan;
  }
	
  public Integer getMindHealth() {
  	return mindHealth;
  }
	
  public void setMindHealth(Integer mindHealth) {
    this.mindHealth = mindHealth;
  }
	
}
